package edo.project.euler.problem2;


/**
 * Problem 2 - Even Fibonacci numbers
 * ==================================
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed 
 * four million, find the sum of the even-valued terms.
 * 
 * @author Edd
 *
 */
public class Problem2BruteForce {

	public int solve(int maximum) {
		int prevTerm = 1;
		int thisTerm = 2;
		int evensums = 0;
		
		while (thisTerm < maximum) {
			if (thisTerm % 2 == 0) {
				evensums += thisTerm;
			}
			int temp = prevTerm + thisTerm;
			prevTerm = thisTerm;
			thisTerm = temp;			
		}
		
		return evensums;
	}
	
	
}
