package edo.project.euler.problem;

/**
/**
 * Problem 2 - Even Fibonacci numbers
 * ==================================
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed 
 * four million, find the sum of the even-valued terms.
 * 
 * @author Edd
 *
 */
public class Problem02Refined {
	
	public int solve(int maximum) {
		return 0;
	}
	
	private int fibonacci(int termInSeq) {
		if(termInSeq == 0) {
			return 0;
		}
		else if(termInSeq == 1) {
			return 1;
		}
		else {
			return fibonacci(termInSeq - 2) + fibonacci(termInSeq - 1); 
		}
	}
}
